services:
  mysql:
    #container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olx-laravel
      TZ: America/Sao_Paulo  
volumes:
  mysql-data: